# Generated by Django 6.0.4 on 2026-04-28 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'For Sale'), ('rehome', 'Rehoming'), ('adopt', 'Adoption'), ('food', 'Bird Food & Supplies')], default='sell', max_length=10),
        ),
        migrations.AlterField(
            model_name='bird',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bird',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bird',
            name='health_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bird',
            name='image',
            field=models.ImageField(upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
